### ISSUE TITLE
sourcemaps

### ISSUE THREAD

**Issue by jeffling** [jeffling/wallaby-vinyl-adapter#1]
without sourcemaps, we won't get the cool code coverage thing wallaby has.

**Comment by jeffling** [comment]
@ArtemGovorov If we would like to be very modular, extracting inline source maps should probably be the job of another preprocessor. On the other hand, since source maps are required for a core functionality of wallaby, should each preprocessor provide it's own source maps?

**Comment by ArtemGovorov** [comment]
@jeffling You are correct, wallaby does need source maps for its core functionality. But I think source maps is an essential cross-cutting concern anyway, as it's not only about wallaby and coverage. 

For example if even some file is marked with `instrument: false`, preprocessed by something that changes its code and then, during the execution some error occurs in the file - the reported error stack will not be correct (there'll be line shift depending on the nature of the transformation). It's not just wallaby, same thing will happen in Karma etc.

For this reason, returning source maps in the preprocessor result (in an object with `code` and `map` or `sourceMap` properties - is highly desirable. But we can't demand it, because there are other types of preprocessors, for example html to JavaScript, where source maps don't make sense.

**Comment by jeffling** [comment]
Maybe we can make a separate source-map extractor preprocessor like https://www.npmjs.com/package/karma-sourcemap-loader?

**Comment by ArtemGovorov** [comment]
I may actually just have to build this kind of extractor right into the core, as it's essential - thanks for sharing!

**Comment by ArtemGovorov** [comment]
https://github.com/wallabyjs/public/issues/23
